version: "3.8"
services:
  angular:
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - "./client:/app"
  lumen:
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./server:/app"
    depends_on:
      - "db"
  db:
    image: mysql:latest
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
       - "./database:/var/lib/mysql/data"
  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
        - "./:/app"
    depends_on:
        - "angular"
        - "lumen"